# Distro-side WSL config
# Place at: /etc/wsl.conf inside WSL

[boot]
systemd=true

[automount]
enabled=true
root=/mnt/
options="metadata,umask=22,fmask=11"
mountFsTab=true

[network]
generateResolvConf=true

[interop]
enabled=true
appendWindowsPath=false
